name: SAGE-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - seaborn
  - pillow
  - pycocotools
  - statsmodels
  - cython
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - alabaster==0.7.16
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - backcall==0.2.0
      - beautifulsoup4
      - black==24.4.2
      - bleach==6.1.0
      - blinker==1.9.0
      - cachetools==5.4.0
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.8
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - dash==3.0.2
      - debugpy==1.8.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docrepr==0.2.0
      - docutils==0.20.1
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - flask==3.0.3
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - fqdn==1.5.1
      - gast==0.6.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.9.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - imageio==2.34.2
      - imagesize==1.4.1
      - imgaug==0.4.0
      - imglyb==2.1.0
      - importlib_metadata
      - importlib_resources
      - iniconfig==2.0.0
      - intersphinx_registry==0.2406.4
      - ipykernel==6.29.5
      - ipyparallel==8.8.0
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipython-sql==0.5.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jgo==1.0.5
      - jinja2==3.1.4
      - jpype1==1.5.0
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter_client==8.6.2
      - jupyter_core==5.7.2
      - jupyter_server==2.14.2
      - jupyter_server_terminals==0.5.3
      - jupyterlab==4.2.3
      - jupyterlab_pygments==0.3.0
      - jupyterlab_server==2.27.3
      - jupyterlab_widgets==3.0.11
      - keras==2.14.0
      - kiwisolver==1.4.5
      - labeling==0.1.14
      - lazy_loader==0.4
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mask-rcnn
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - munkres==1.1.4
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - narwhals==1.33.0
      - nbclassic
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - notebook
      - notebook_shim==0.2.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvcc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.16.5
      - oauthlib==3.2.2
      - open3d==0.19.0
      - opencv-contrib-python==4.8.0.76
      - opencv-python==4.8.0.76
      - opt-einsum==3.3.0
      - optree==0.12.1
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pathspec==0.12.1
      - pkgutil_resolve_name
      - platformdirs==4.2.2
      - plotly==6.0.1
      - pluggy==1.5.0
      - prettytable==3.10.2
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1_modules==0.4.0
      - pycparser==2.22
      - pygments==2.18.0
      - pyimagej==1.4.1
      - pyquaternion==0.9.9
      - pyrsistent
      - pytest==8.2.2
      - pytest-asyncio==0.21.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.19.0
      - rsa==4.9
      - scyjava==1.10.0
      - send2trash==1.8.3
      - shapely==2.0.5
      - snowballstemmer==2.2.0
      - soupsieve
      - sphinx==7.4.5
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.31
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - stereofractanalyzer==1.0.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorrt==8.5.3.1
      - termcolor==2.4.0
      - terminado==0.18.1
      - testpath==0.6.0
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tqdm==4.66.4
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.2
      - webcolors==24.6.0
      - webencodings
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.14.1
      - xarray==2024.6.0
  # The following were editable/local installs in your pip freeze.
  # Replace with a VCS URL (e.g., git+https://...) or package name if available:
  #   - -e /home/timd/Desktop/maskrcnn