name: SAGE-gpu-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - numpy=1.23.*          # keep np.bool, np.int, etc. working
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - opencv
  - pillow
  - tqdm
  - cython
  - hdf5=1.14.2           # align with h5py build
  - h5py=3.9.*            # built against HDF5 1.14.2
  - pycocotools
  - pip:
      - tensorflow==2.10.*
      - keras==2.10.*
      - protobuf<3.20.0   # TF 2.10 compatible
      - stereofractanalyzer==1.0.0
